# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtocolCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtocolCommon.proto',
  package='ProtocolCommon',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14ProtocolCommon.proto\x12\x0eProtocolCommon\"<\n\x08RoleInfo\x12\x0e\n\x06roleid\x18\x01 \x01(\x04\x12\x10\n\x08rolename\x18\x02 \x01(\t\x12\x0e\n\x06iconid\x18\x03 \x01(\r*\x84\x02\n\nServerType\x12\t\n\x05login\x10\x00\x12\x0b\n\x07gateway\x10\x01\x12\t\n\x05world\x10\x02\x12\t\n\x05match\x10\x03\x12\x0b\n\x07\x66orward\x10\x04\x12\x12\n\x0e\x62\x61ttle_gateway\x10\x05\x12\n\n\x06\x62\x61ttle\x10\x06\x12\x08\n\x04team\x10\x07\x12\n\n\x06\x66riend\x10\x08\x12\n\n\x06\x64\x61\x65mon\x10\t\x12\t\n\x05robot\x10\n\x12\x08\n\x04mail\x10\x0b\x12\x06\n\x02gm\x10\r\x12\x07\n\x03pay\x10\x0e\x12\t\n\x05scene\x10\x0f\x12\n\n\x06social\x10\x10\x12\x08\n\x04idip\x10\x65\x12\n\n\x06\x63lient\x10\x66\x12\x0f\n\x0bmultiserver\x10g\x12\t\n\x05micro\x10h\x12\n\n\x06paysdk\x10i*\xae\x01\n\x08ItemType\x12\r\n\tItem_none\x10\x00\x12\x0c\n\x08Item_box\x10\x01\x12\x11\n\rItem_exchange\x10\x02\x12\x0f\n\x0bItem_effect\x10\x03\x12\r\n\tItem_card\x10\x04\x12\r\n\tItem_chip\x10\x05\x12\x0f\n\x0bItem_common\x10\x06\x12\x0c\n\x08Item_exp\x10\x08\x12\x0e\n\nItem_money\x10\t\x12\x14\n\x10Item_jigsaw_chip\x10\n*\'\n\x07SubType\x12\x0c\n\x08Sub_none\x10\x00\x12\x0e\n\nSeason_exp\x10\n*\xbc\x01\n\nObjectType\x12\x08\n\x04None\x10\x00\x12\x08\n\x04Hero\x10\x01\x12\x08\n\x04Skin\x10\x02\x12\x08\n\x04Item\x10\x03\x12\x0e\n\nAvatarPart\x10\x04\x12\x07\n\x03\x45gg\x10\x05\x12\x07\n\x03Pet\x10\x06\x12\x0e\n\nAvatarSuit\x10\x07\x12\r\n\tShopGoods\x10\x08\x12\x0c\n\x08LevelExp\x10\t\x12\r\n\tSeasonExp\x10\n\x12\r\n\tActiveExp\x10\x0b\x12\x08\n\x04\x45moj\x10\x0c\x12\x0f\n\x0bJigsaw_Chip\x10\r*B\n\x10ObjectSourceType\x12\x0f\n\x0bSource_None\x10\x00\x12\x0c\n\x08\x45xchange\x10\x01\x12\x0f\n\x0b\x45xtraReward\x10\x02*@\n\rKick_Off_Type\x12\x0b\n\x07gm_kick\x10\x00\x12\x0e\n\nghome_kick\x10\x01\x12\x12\n\x0ereconnect_kick\x10\x02\x62\x06proto3')
)

_SERVERTYPE = _descriptor.EnumDescriptor(
  name='ServerType',
  full_name='ProtocolCommon.ServerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='login', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gateway', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='world', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='match', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='forward', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='battle_gateway', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='battle', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='team', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='friend', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='daemon', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='robot', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='mail', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gm', index=12, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pay', index=13, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='scene', index=14, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='social', index=15, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='idip', index=16, number=101,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='client', index=17, number=102,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='multiserver', index=18, number=103,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='micro', index=19, number=104,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='paysdk', index=20, number=105,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=103,
  serialized_end=363,
)
_sym_db.RegisterEnumDescriptor(_SERVERTYPE)

ServerType = enum_type_wrapper.EnumTypeWrapper(_SERVERTYPE)
_ITEMTYPE = _descriptor.EnumDescriptor(
  name='ItemType',
  full_name='ProtocolCommon.ItemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Item_none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_box', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_exchange', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_effect', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_card', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_chip', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_common', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_exp', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_money', index=8, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item_jigsaw_chip', index=9, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=366,
  serialized_end=540,
)
_sym_db.RegisterEnumDescriptor(_ITEMTYPE)

ItemType = enum_type_wrapper.EnumTypeWrapper(_ITEMTYPE)
_SUBTYPE = _descriptor.EnumDescriptor(
  name='SubType',
  full_name='ProtocolCommon.SubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Sub_none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Season_exp', index=1, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=542,
  serialized_end=581,
)
_sym_db.RegisterEnumDescriptor(_SUBTYPE)

SubType = enum_type_wrapper.EnumTypeWrapper(_SUBTYPE)
_OBJECTTYPE = _descriptor.EnumDescriptor(
  name='ObjectType',
  full_name='ProtocolCommon.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hero', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Skin', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Item', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AvatarPart', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Egg', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Pet', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AvatarSuit', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ShopGoods', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LevelExp', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SeasonExp', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ActiveExp', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Emoj', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jigsaw_Chip', index=13, number=13,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=584,
  serialized_end=772,
)
_sym_db.RegisterEnumDescriptor(_OBJECTTYPE)

ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
_OBJECTSOURCETYPE = _descriptor.EnumDescriptor(
  name='ObjectSourceType',
  full_name='ProtocolCommon.ObjectSourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Source_None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Exchange', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExtraReward', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=774,
  serialized_end=840,
)
_sym_db.RegisterEnumDescriptor(_OBJECTSOURCETYPE)

ObjectSourceType = enum_type_wrapper.EnumTypeWrapper(_OBJECTSOURCETYPE)
_KICK_OFF_TYPE = _descriptor.EnumDescriptor(
  name='Kick_Off_Type',
  full_name='ProtocolCommon.Kick_Off_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='gm_kick', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ghome_kick', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='reconnect_kick', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=842,
  serialized_end=906,
)
_sym_db.RegisterEnumDescriptor(_KICK_OFF_TYPE)

Kick_Off_Type = enum_type_wrapper.EnumTypeWrapper(_KICK_OFF_TYPE)
login = 0
gateway = 1
world = 2
match = 3
forward = 4
battle_gateway = 5
battle = 6
team = 7
friend = 8
daemon = 9
robot = 10
mail = 11
gm = 13
pay = 14
scene = 15
social = 16
idip = 101
client = 102
multiserver = 103
micro = 104
paysdk = 105
Item_none = 0
Item_box = 1
Item_exchange = 2
Item_effect = 3
Item_card = 4
Item_chip = 5
Item_common = 6
Item_exp = 8
Item_money = 9
Item_jigsaw_chip = 10
Sub_none = 0
Season_exp = 10
globals()['None'] = 0
Hero = 1
Skin = 2
Item = 3
AvatarPart = 4
Egg = 5
Pet = 6
AvatarSuit = 7
ShopGoods = 8
LevelExp = 9
SeasonExp = 10
ActiveExp = 11
Emoj = 12
Jigsaw_Chip = 13
Source_None = 0
Exchange = 1
ExtraReward = 2
gm_kick = 0
ghome_kick = 1
reconnect_kick = 2



_ROLEINFO = _descriptor.Descriptor(
  name='RoleInfo',
  full_name='ProtocolCommon.RoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roleid', full_name='ProtocolCommon.RoleInfo.roleid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rolename', full_name='ProtocolCommon.RoleInfo.rolename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iconid', full_name='ProtocolCommon.RoleInfo.iconid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['RoleInfo'] = _ROLEINFO
DESCRIPTOR.enum_types_by_name['ServerType'] = _SERVERTYPE
DESCRIPTOR.enum_types_by_name['ItemType'] = _ITEMTYPE
DESCRIPTOR.enum_types_by_name['SubType'] = _SUBTYPE
DESCRIPTOR.enum_types_by_name['ObjectType'] = _OBJECTTYPE
DESCRIPTOR.enum_types_by_name['ObjectSourceType'] = _OBJECTSOURCETYPE
DESCRIPTOR.enum_types_by_name['Kick_Off_Type'] = _KICK_OFF_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoleInfo = _reflection.GeneratedProtocolMessageType('RoleInfo', (_message.Message,), {
  'DESCRIPTOR' : _ROLEINFO,
  '__module__' : 'ProtocolCommon_pb2'
  # @@protoc_insertion_point(class_scope:ProtocolCommon.RoleInfo)
  })
_sym_db.RegisterMessage(RoleInfo)


# @@protoc_insertion_point(module_scope)
